In [ ]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 2d list has row of same length
print(a)
for row in a:
    print(row)
print(len(a))
print(a[0])
print(a[0][2])
print(a[2][1])

In [ ]:
a = [[1], [2, 3], [], [4, 5, 6]] # a 2d list that has row of different length
for row in a:
    print(row)

In [ ]:
students = [['John', 'GCH0001', 3.5], ['Jane', 'GCH0002', 3.9], ['Jack', 'GCH0003', 3.2]]
for st in students:
    print(st[0], st[1], st[2])

In [ ]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]
for row in a:
    print(row)
for row in a[2:4]:
    print(row)

In [ ]:
import random as rd
matrix = [rd.sample(range(10, 100), 5),
          rd.sample(range(10, 100), 5),
          rd.sample(range(10, 100), 5),
          rd.sample(range(10, 100), 5),
          rd.sample(range(10, 100), 5)]

def print_matrix(m):
    for row in m:
        print(row)

print_matrix(matrix)

In [15]:
# Get 3 middle rows in as many ways as you can
print_matrix(matrix[1:4])
print('----------------')
print_matrix(matrix[1:-1])
# Get 2 last rows in as many ways as you can
print('----------------')
print_matrix(matrix[-2:])
print('----------------')
print_matrix(matrix[3:])

[12, 43, 18, 22, 99]
[82, 76, 33, 67, 45]
[96, 74, 11, 84, 24]
----------------
[12, 43, 18, 22, 99]
[82, 76, 33, 67, 45]
[96, 74, 11, 84, 24]
----------------
[96, 74, 11, 84, 24]
[99, 19, 50, 62, 44]
----------------
[96, 74, 11, 84, 24]
[99, 19, 50, 62, 44]


In [16]:
n = int(input('Enter row n: '))
print(f'Sum of row {n} is {sum(matrix[n])}')
print(f'Min of row {n} is {min(matrix[n])}')
print(f'Max of row {n} is {max(matrix[n])}')

Sum of row 3 is 289
Min of row 3 is 11
Max of row 3 is 96


In [17]:
print(f'Sorted row {n} is {sorted(matrix[n])}')

Sorted row 3 is [11, 24, 74, 84, 96]


In [4]:
# products = ['pen', 'pencil', 'notebook', 'eraser', 'ruler', 'book']
# prices = [10, 5, 20, 2, 8, 25]
# solds = [110, 180, 58, 150, 120, 30]
product_solds = [['pen', 10, 110],
                 ['pencil', 5, 180],
                 ['notebook', 20, 58],
                 ['eraser', 2, 150],
                 ['ruler', 8, 120],
                 ['book', 25, 30]]

# Find the cheapest product
min_price = product_solds[0][1]
i_min = 0
for i in range(len(product_solds)):
    if product_solds[i][1] < min_price:
        min_price = product_solds[i][1]
        i_min = i
print(f'Cheapest product is {product_solds[i_min][0]} with price ${min_price}')
# Find the product that is sold the most
max_row = product_solds[0]
for row in product_solds:
    if row[2] > max_row[2]:
        max_row = row
print(f'The product that is sold the most is {max_row[0]} with {max_row[2]} solds')
# Calculate average income of all products
total = 0
for row in product_solds:
    total += row[1] * row[2]
print(f'Average income of all products is ${total / len(product_solds):.2f}')
# Count how many products that has income less than the average income
avg_income = total / len(product_solds)
count = 0
for row in product_solds:
    if row[1] * row[2] < avg_income:
        count += 1
print(f'There are {count} products that has income less than the average income')

Cheapest product is eraser with price $2
The product that is sold the most is pencil with 180 solds
Average income of all products is $861.67
There are 2 products that has income less than the average income


In [ ]:
import numpy as np
# Create array from list
a = [1, 2, 3, 4]
b = np.array(a)
print(a, b)
print(b[0], b[-1])
print(b[1:3])

In [12]:
# Create array using arange function => similar to range
a = np.arange(10)
print(a)
b = np.arange(10, 20)
print(b)
c = np.arange(10, 20, 2)
print(c)
d = np.arange(0, 1, 0.1)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [20]:
# Create array using linspace function
a = np.linspace(0, 9, 10, dtype=int)
print(a)
b = np.linspace(0, 10, 10, endpoint=False)
print(b)
c = np.linspace(10, 20, 5)
print(c)
d = np.linspace(0, 1, 10, endpoint=False)   
print(d)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10.  12.5 15.  17.5 20. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [21]:
# Generate 13 numbers among 0.1 and 0.5
a, step = np.linspace(0.1, 0.5, 13, retstep=True)
print(a)
print(step)

[0.1        0.13333333 0.16666667 0.2        0.23333333 0.26666667
 0.3        0.33333333 0.36666667 0.4        0.43333333 0.46666667
 0.5       ]
0.03333333333333333


In [24]:
a = np.logspace(1, 10, 10, base=2, dtype=int)
print(a)
a = np.logspace(1, 10, 10, dtype=int)
print(a)

[   2    4    8   16   32   64  128  256  512 1024]
[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 10000000000]


In [25]:
# Using logspace generate following numbers: 27, 81, 243, 729, 2187, 6561
print(np.logspace(3, 8, 6, base=3, dtype=int))

[  27   81  243  729 2187 6561]


In [27]:
print(np.zeros(5))
print(np.ones((5, 5)) * 2)

[0. 0. 0. 0. 0.]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [31]:
# Array arithmetics operations
# Array +-*/%... Array => element-wise operations on arrays of the same size
a = np.array([1, 2, 3, 4])  
b = np.array([5, 6, 7, 8])
print(a + b)    # [6 8 10 12] 
print(a - b)    # [-4 -4 -4 -4] 

[ 6  8 10 12]
[-4 -4 -4 -4]


In [35]:
# Array +-*/%... Scalar => element-wise operations on arrays and a scalar
print(a + 2)
print(a - 2)
print(2 ** a)
print(2 ** a + np.sin(a))

[3 4 5 6]
[-1  0  1  2]
[ 2  4  8 16]
[ 2.84147098  4.90929743  8.14112001 15.2431975 ]
