In [ ]:
import numpy as np

numbers = np.random.randint(1, 100, 10)
print(numbers)

evens = numbers[numbers % 2 == 0]
print(evens)

print(numbers % 2 == 0)

odds = numbers[numbers % 2 == 1]
print(odds)

In [ ]:
numbers = np.random.randint(-100, 100, 15)
print(numbers)
# get positive numbers
positives = numbers[numbers > 0]
print(positives)
# get negative numbers
negatives = numbers[numbers < 0]
print(negatives)

In [ ]:
# numbers[numbers < 0] = 0
numbers[numbers < 0] *= -1
print(numbers)

In [11]:
# Generate 20 floating random numbers between -1 and 1
numbers = np.random.randint(-100, 100, 20) / 100
print(numbers)
# Convert negative numbers to -1, positive and zero numbers to 1
numbers[numbers < 0] = -1
numbers[numbers >= 0] = 1
print(numbers)

[-0.11  0.35 -0.79  0.37  0.11 -0.79 -0.71 -0.9  -0.76  0.91  0.14  0.73
  0.49  0.91  0.17  0.89  0.63  0.08  0.67  0.88]
[-1.  1. -1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]


In [26]:
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 
v = np.array([0, 0., 0, 0, 0, 0, 0])
for i in range(1, len(y)):
    v[i] = (y[i] - y[i - 1]) / (t[i] - t[i - 1])
    print(f'{v[i]:.2f}', end=' ')

v[1:] = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

2.65 7.25 11.80 13.79 20.85 17.38 [ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [20]:
names = ['Paul Lambert', '', 'Mike Tyson', 'Anthony Compa', '', 'Anna']
names = np.array(names)
names[names == ''] = 'John Doe'
print(names)

['Paul Lambert' 'John Doe' 'Mike Tyson' 'Anthony Compa' 'John Doe' 'Anna']


In [23]:
ages = np.array([12, -29, 88, 100, 170, 43])
ages[ages < 0] = 0
ages[ages > 150] = 150
print(ages)

[ 12   0  88 100 150  43]


In [27]:
a = [29, '29', 29.0]
b = np.array(a)
print(b)

['29' '29' '29.0']


In [29]:
print(f'Longest name: {max(names, key=len)}')
print(f'Shortest name: {min(names, key=len)}')

Longest name: Anthony Compa
Shortest name: Anna


In [33]:
# 2D array: all rows have the same length
# Create 2d array from 2d list
a = [[1, 2, 3], [4, 5, 6]]
b = np.array(a)
print(b)
print(len(b), np.size(b), np.shape(b))
c = np.reshape(b, (3, 2))
print(c, '\n-------')
e = np.reshape(b, (6, 1))
print(e, '\n-------')
f = np.reshape(b, (1, 6))
print(f, '\n-------')

[[1 2 3]
 [4 5 6]]
2 6 (2, 3)
[[1 2]
 [3 4]
 [5 6]] 
-------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
-------
[[1 2 3 4 5 6]] 
-------


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.shape(a))
print(np.shape(f))
print(np.shape(e))

(6,)
(1, 6)
(6, 1)


In [41]:
a = np.random.randint(10, 100, (5, 5))
print(a)
print(a[:, 1:3])

[[49 50 34 99 70]
 [74 15 59 89 58]
 [18 63 55 42 58]
 [17 73 11 50 67]
 [95 13 75 73 32]]
[[50 34]
 [15 59]
 [63 55]
 [73 11]
 [13 75]]


In [42]:
print(a[2:4, 2:4])

[[55 42]
 [11 50]]


In [44]:
print(a[0, -1], a[0][-1])

70 70


In [47]:
print(a)
a[0] = 0
print(a)
a[:2, 3:] = 0
print(a)

[[ 0  0  0  0  0]
 [74 15 59 89 58]
 [18 63 55 42 58]
 [17 73 11 50 67]
 [95 13 75 73 32]]
[[ 0  0  0  0  0]
 [74 15 59 89 58]
 [18 63 55 42 58]
 [17 73 11 50 67]
 [95 13 75 73 32]]
[[ 0  0  0  0  0]
 [74 15 59  0  0]
 [18 63 55 42 58]
 [17 73 11 50 67]
 [95 13 75 73 32]]


In [49]:
print(np.zeros((4, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
a = np.ones((8, 8), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [55]:
a = np.zeros((8, 8), dtype=int)
a[::7, :] = 1
a[1:-1, ::7] = 1
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [56]:
a = np.zeros((8, 8), dtype=int)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [57]:
a = np.ones((8, 8), dtype=int)
a[::2, 1::2] = 0
a[1::2, ::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [58]:
a = ([1, 0] * 4 + [0, 1] * 4) * 4
a = np.reshape(a, (8, 8))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [59]:
a = np.random.randint(10, 99, (8, 8))
print(a)

[[20 67 78 82 80 37 21 92]
 [79 25 69 85 40 14 59 30]
 [86 40 12 98 62 37 31 55]
 [87 71 97 16 54 24 29 89]
 [29 87 63 67 71 86 95 24]
 [10 35 42 24 51 65 86 42]
 [66 64 14 13 47 84 43 27]
 [85 73 32 60 80 40 36 34]]


In [60]:
a[a % 3 != 0] *= -1
print(a)

[[-20 -67  78 -82 -80 -37  21 -92]
 [-79 -25  69 -85 -40 -14 -59  30]
 [-86 -40  12 -98 -62 -37 -31 -55]
 [ 87 -71 -97 -16  54  24 -29 -89]
 [-29  87  63 -67 -71 -86 -95  24]
 [-10 -35  42  24  51 -65 -86  42]
 [ 66 -64 -14 -13 -47  84 -43  27]
 [-85 -73 -32  60 -80 -40  36 -34]]
