In [3]:
def my_sort(items, compare=lambda a, b: a > b):
    for i in range(len(items)-1):
        for j in range(i+1, len(items)):
            if compare(items[i], items[j]):
                items[i], items[j] = items[j], items[i]
    return items

In [4]:
import numpy as np
numbers = np.random.randint(10, 100, 10)

my_sort(numbers)
print(numbers)

[22 26 36 42 42 46 75 76 93 96]


In [5]:
my_sort(numbers, lambda a, b: a < b)
print(numbers)

[96 93 76 75 46 42 42 36 26 22]


In [6]:
# Sort by sum of digits
my_sort(numbers, lambda a, b: a % 10 + a // 10 > b % 10 + b // 10)
print(numbers)

[22 42 42 26 36 46 93 75 76 96]


In [7]:
cube = lambda x: x ** 3
print(cube(2))

8


In [8]:
product_solds = [['pen', 10, 110],
                 ['pencil', 5, 180],
                 ['notebook', 20, 58],
                 ['eraser', 2, 150],
                 ['ruler', 8, 120],
                 ['book', 25, 30]]

# Sort products by price
my_sort(product_solds, lambda a, b: a[1] > b[1])
print(product_solds)
# Sort products by sold
my_sort(product_solds, lambda a, b: a[2] > b[2])
print(product_solds)
# Sort products by revenue
my_sort(product_solds, lambda a, b: a[1] * a[2] > b[1] * b[2])
print(product_solds)

[['eraser', 2, 150], ['pencil', 5, 180], ['ruler', 8, 120], ['pen', 10, 110], ['notebook', 20, 58], ['book', 25, 30]]
[['book', 25, 30], ['notebook', 20, 58], ['pen', 10, 110], ['ruler', 8, 120], ['eraser', 2, 150], ['pencil', 5, 180]]
[['eraser', 2, 150], ['book', 25, 30], ['pencil', 5, 180], ['ruler', 8, 120], ['pen', 10, 110], ['notebook', 20, 58]]


In [18]:
numbers = np.random.randint(10, 100, 20)
print(numbers)
# Print even numbers
for n in numbers:
    if n % 2 == 0:
        print(n, end=' ')
print()
evens = [n for n in numbers if n % 2 == 0]
print(evens)
evens = numbers[numbers % 2 == 0]
print(evens)
evens = list(filter(lambda n: n % 2 == 0, numbers))
print(evens)

for n in filter(lambda n: n % 2 == 0, numbers):
    print(n, end=' ')

[39 69 66 53 86 19 93 48 48 72 62 74 23 94 74 97 76 38 51 58]
66 86 48 48 72 62 74 94 74 76 38 58 
[66, 86, 48, 48, 72, 62, 74, 94, 74, 76, 38, 58]
[66 86 48 48 72 62 74 94 74 76 38 58]
[66, 86, 48, 48, 72, 62, 74, 94, 74, 76, 38, 58]
66 86 48 48 72 62 74 94 74 76 38 58 

In [17]:
# Calculate sum of even numbers
s = 0
for n in numbers:
    if n % 2 == 0:
        s += n
print(s)
s = sum([n for n in numbers if n % 2 == 0])
print(s)
s = sum(numbers[numbers % 2 == 0])
print(s)
s = sum(filter(lambda n: n % 2 == 0, numbers))

532
532


In [20]:
numbers = np.random.randint(-100, 100, 20)
print(numbers)

# Find max of negative numbers
print(max(filter(lambda n: n < 0, numbers)))
# Find min of positive numbers
print(min(filter(lambda n: n > 0, numbers)))

[  6 -63 -20 -66  94 -22  11   2  31 -73 -19  29 -65  80  19  -9 -39  38
  67  63]
-9
2


In [21]:
# map function: apply a function to each item of a sequence
pos_numbers = list(map(lambda n: n if n > 0 else -n, numbers))
print(pos_numbers)

[6, 63, 20, 66, 94, 22, 11, 2, 31, 73, 19, 29, 65, 80, 19, 9, 39, 38, 67, 63]


In [22]:
names = ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr']
# Get first names (using map)
first_names = list(map(lambda n: n.split()[0], names))
print(first_names)
# Get last names (using map)
last_names = list(map(lambda n: n.split()[1], names))
print(last_names)

['John', 'Paul', 'George', 'Ringo']
['Lennon', 'McCartney', 'Harrison', 'Starr']


In [26]:
# Find product with max price
max_product = max(product_solds, key=lambda p: p[1])
print(max_product)
# Find product with max sold
max_product = max(product_solds, key=lambda p: p[2])
print(max_product)
# Find min revenue of products that has sold >= 100
print(min(filter(lambda p: p[2] >= 100, product_solds), key=lambda p: p[1] * p[2]))
# Calculate total revenue of products that has price >= 10
print(sum(map(lambda p: p[1] * p[2], filter(lambda p: p[1] >= 10, product_solds))))
print(sum(map(lambda p: p[1] * p[2] if p[1] >= 10 else 0, product_solds)))

['book', 25, 30]
['pencil', 5, 180]
['eraser', 2, 150]
3010
3010
