In [3]:
def my_sort(items, compare=lambda a, b: a > b):
    for i in range(len(items)-1):
        for j in range(i+1, len(items)):
            if compare(items[i], items[j]):
                items[i], items[j] = items[j], items[i]
    return items

In [4]:
import numpy as np
numbers = np.random.randint(10, 100, 10)

my_sort(numbers)
print(numbers)

[22 26 36 42 42 46 75 76 93 96]


In [5]:
my_sort(numbers, lambda a, b: a < b)
print(numbers)

[96 93 76 75 46 42 42 36 26 22]


In [6]:
# Sort by sum of digits
my_sort(numbers, lambda a, b: a % 10 + a // 10 > b % 10 + b // 10)
print(numbers)

[22 42 42 26 36 46 93 75 76 96]


In [7]:
cube = lambda x: x ** 3
print(cube(2))

8


In [8]:
product_solds = [['pen', 10, 110],
                 ['pencil', 5, 180],
                 ['notebook', 20, 58],
                 ['eraser', 2, 150],
                 ['ruler', 8, 120],
                 ['book', 25, 30]]

# Sort products by price
my_sort(product_solds, lambda a, b: a[1] > b[1])
print(product_solds)
# Sort products by sold
my_sort(product_solds, lambda a, b: a[2] > b[2])
print(product_solds)
# Sort products by revenue
my_sort(product_solds, lambda a, b: a[1] * a[2] > b[1] * b[2])
print(product_solds)

[['eraser', 2, 150], ['pencil', 5, 180], ['ruler', 8, 120], ['pen', 10, 110], ['notebook', 20, 58], ['book', 25, 30]]
[['book', 25, 30], ['notebook', 20, 58], ['pen', 10, 110], ['ruler', 8, 120], ['eraser', 2, 150], ['pencil', 5, 180]]
[['eraser', 2, 150], ['book', 25, 30], ['pencil', 5, 180], ['ruler', 8, 120], ['pen', 10, 110], ['notebook', 20, 58]]


In [18]:
numbers = np.random.randint(10, 100, 20)
print(numbers)
# Print even numbers
for n in numbers:
    if n % 2 == 0:
        print(n, end=' ')
print()
evens = [n for n in numbers if n % 2 == 0]
print(evens)
evens = numbers[numbers % 2 == 0]
print(evens)
evens = list(filter(lambda n: n % 2 == 0, numbers))
print(evens)

for n in filter(lambda n: n % 2 == 0, numbers):
    print(n, end=' ')

[39 69 66 53 86 19 93 48 48 72 62 74 23 94 74 97 76 38 51 58]
66 86 48 48 72 62 74 94 74 76 38 58 
[66, 86, 48, 48, 72, 62, 74, 94, 74, 76, 38, 58]
[66 86 48 48 72 62 74 94 74 76 38 58]
[66, 86, 48, 48, 72, 62, 74, 94, 74, 76, 38, 58]
66 86 48 48 72 62 74 94 74 76 38 58 

In [17]:
# Calculate sum of even numbers
s = 0
for n in numbers:
    if n % 2 == 0:
        s += n
print(s)
s = sum([n for n in numbers if n % 2 == 0])
print(s)
s = sum(numbers[numbers % 2 == 0])
print(s)
s = sum(filter(lambda n: n % 2 == 0, numbers))

532
532


In [20]:
numbers = np.random.randint(-100, 100, 20)
print(numbers)

# Find max of negative numbers
print(max(filter(lambda n: n < 0, numbers)))
# Find min of positive numbers
print(min(filter(lambda n: n > 0, numbers)))

[  6 -63 -20 -66  94 -22  11   2  31 -73 -19  29 -65  80  19  -9 -39  38
  67  63]
-9
2


In [21]:
# map function: apply a function to each item of a sequence
pos_numbers = list(map(lambda n: n if n > 0 else -n, numbers))
print(pos_numbers)

[6, 63, 20, 66, 94, 22, 11, 2, 31, 73, 19, 29, 65, 80, 19, 9, 39, 38, 67, 63]


In [22]:
names = ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr']
# Get first names (using map)
first_names = list(map(lambda n: n.split()[0], names))
print(first_names)
# Get last names (using map)
last_names = list(map(lambda n: n.split()[1], names))
print(last_names)

['John', 'Paul', 'George', 'Ringo']
['Lennon', 'McCartney', 'Harrison', 'Starr']


In [26]:
# Find product with max price
max_product = max(product_solds, key=lambda p: p[1])
print(max_product)
# Find product with max sold
max_product = max(product_solds, key=lambda p: p[2])
print(max_product)
# Find min revenue of products that has sold >= 100
print(min(filter(lambda p: p[2] >= 100, product_solds), key=lambda p: p[1] * p[2]))
# Calculate total revenue of products that has price >= 10
print(sum(map(lambda p: p[1] * p[2], filter(lambda p: p[1] >= 10, product_solds))))
print(sum(map(lambda p: p[1] * p[2] if p[1] >= 10 else 0, product_solds)))

['book', 25, 30]
['pencil', 5, 180]
['eraser', 2, 150]
3010
3010


In [31]:
employees = [['John', '0876523213', 1400],
             ['Mary', '0876523214', 15000],
             ['', '0876523215', 100],
             ['Tommmmmmmmmmmmmmmmmmmmm', '0876523DDD', 1700],
             ['', '087A23B17', 800],
             ['Jill', '0876523218', -900]]

fix_nothing = lambda e: e
def clean_employees(employees, fix=fix_nothing):
    for i in range(len(employees)):
        employees[i] = fix(employees[i])
def print_employees(employees):
    for e in employees:
        print(e)
# Empty name can be changed to a default name (John Doe)
clean_employees(employees, fix=lambda e: ['John Doe', e[1], e[2]] if e[0] == '' else e)
print_employees(employees)

['John', '0876523213', 1400]
['Mary', '0876523214', 15000]
['John Doe', '0876523215', 100]
['Tommmmmmmmmmmmmmmmmmmmm', '0876523DDD', 1700]
['John Doe', '087A23B17', 800]
['Jill', '0876523218', -900]


In [ ]:
# Too long name should be truncated (max 20 characters)
clean_employees(employees, fix=lambda e: [e[0][:20], e[1], e[2]])
print_employees(employees)

In [ ]:
# Phone must be digits.  Any non-digit should change to 0.  (i.e 012ab34 => 0120034)
def fix_phone_zero(e):
    phone = [c if c.isdigit() else '0' for c in e[1]]
    return [e[0], ''.join(phone), e[2]]
clean_employees(employees, fix=fix_phone_zero)
print_employees(employees)

In [32]:
# Phone must be digits, any non-digit should change to a previous digit (or 0 if not)
def fix_phone_previous(e):
    phone = [c for c in e[1]]
    if not phone[0].isdigit():
        phone[0] = '0'
    for i in range(1, len(phone)):
        if not phone[i].isdigit():
            phone[i] = phone[i-1]
    return [e[0], ''.join(phone), e[2]]
clean_employees(employees, fix=fix_phone_previous)
print_employees(employees)

['John', '0876523213', 1400]
['Mary', '0876523214', 15000]
['John Doe', '0876523215', 100]
['Tommmmmmmmmmmmmmmmmmmmm', '0876523333', 1700]
['John Doe', '087723317', 800]
['Jill', '0876523218', -900]


In [ ]:
# Valid salary is in range [200, 2000]. Any invalid salary should change to 200 or 2000 correspondingly
clean_employees(employees, lambda e: [e[0], e[1], 200 if e[2] < 200 else 2000 if e[2] > 2000 else e[2]])

In [36]:
# Valid salary is in range [200, 2000]. Any invalid salary should change to mean of valid salary
mean_valid_salary = np.mean(list(map(lambda e: e[2], filter(lambda e: 200 <= e[2] <= 2000, employees))))
print(mean_valid_salary)
clean_employees(employees, lambda e: [e[0], e[1], mean_valid_salary if e[2] < 200 or e[2] > 2000 else e[2]])
print_employees(employees)

1300.0
['John', '0876523213', 1400]
['Mary', '0876523214', 1300.0]
['John Doe', '0876523215', 1300.0]
['Tommmmmmmmmmmmmmmmmmmmm', '0876523333', 1700]
['John Doe', '087723317', 800]
['Jill', '0876523218', 1300.0]
